apiVersion : apps/v1
kind: Deployment
metadata:
  name: "phpinfo"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "phpinfo"
  template:
    metadata:
      labels:
        app: "phpinfo"
    spec:
      containers:
        - name: "phpinfo"
          image: "clustercr01.azurecr.io/phpinfo"
          ports:
          - containerPort: 80
