apiVersion: v1
kind: Service
metadata:
    name: "phpinfo"
    labels:
        app: "phpinfo"
spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: apache
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: node
    selector:
        app: "phpinfo"
    type: LoadBalancer
