on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Collecting ACR information
      id: collecting-acr-info
      run: |
        echo "::set-output name=acr_username::`az acr credential show -n gableesaving -g aks01 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n gableesaving -g aks01 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n gableesaving -g aks01 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: gableesaving.azurecr.io
        username: ${{ steps.collecting-acr-info.outputs.acr_username }}
        password: ${{ steps.collecting-acr-info.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t gableesaving.azurecr.io/phpinfo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push gableesaving.azurecr.io/phpinfo:${{ github.sha }}

    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_cluster01_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep app03 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace app03`
        fi

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: app03
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          gableesaving.azurecr.io/sample/phpinfo:${{ github.sha }}

